### ISSUE TITLE
Regarding the ExpressionControl plugin

### ISSUE THREAD

**Issue by HanYuanyi** [starstormhun/StarPlugins#12]
Regarding the ExpressionControl plugin:

After testing, it is indeed possible to control male facial expressions in the studio.

However, when entering Free H mode, attempting to change the male's facial expression does not succeed. The male's facial expression remains locked, with only the blinking and blushing settings being adjustable.

Is there a solution to this issue?
Thank you very much

**Comment by starstormhun** [comment]
The plugin is not meant to be used in Maker/H-Scenes, its functionality as far as I can tell in those game modes is basically coincidental. For example, in H-scenes, the game overrides expressions regularly, whether on a male or a female, and blushing cannot be controlled in Maker.
This is not easily solvable.

**Comment by HanYuanyi** [comment]
> 该插件不打算在Maker/H-Scenes中使用，据我所知，它在这些游戏模式中的功能基本上是巧合的。例如，在H场景中，游戏会定期覆盖表情，无论是男性还是女性，在Maker中无法控制脸红。 这个问题不容易解决。

Here's a translation of your sentence into English:

"My plugin environment can control blushing and also the facial expressions of women during spontaneous sexual arousal. The facial expression cycle of women can be locked by the plugin, but it cannot be used for men. Are there any parts of the code for women that could be referenced?"
