### ISSUE TITLE
Performancer Plugin v1.0.0 Fingers FK Bones bug

### ISSUE THREAD

**Issue by AsintotoX** [starstormhun/StarPlugins#21]
The new performancer plugin causes a bug where the finger bones (thumb 1-2-3, index etc.) don't move together with the hand. 
To make it more clear: I open a scene where the hand is already positioned, and if I move it, the fingers'  white circles (FK Bones?) stay in the original position. This does not impede the rotation of the fingers though.

**Comment by starstormhun** [comment]
Good catch!
I've added it to my todo list
