### ISSUE TITLE
Light Settings (v1.1) can't load image into cookie in KK studio

### ISSUE THREAD

**Issue by cabal8413** [starstormhun/StarPlugins#24]
Hi, sorry to bother you. I'd want to report that I can't LOAD any image into cookie of Light Settings (v1.1) in KK studio.
Already try what you say in the mod-release forum (black/transparent for spot lights), but they don't work.

**Comment by starstormhun** [comment]
The shader you're lighting might not support cookies, or the light you're using might not be lighting the appropriate layers (check culling mask), or the cookie size of the light might be set to 0. The cookies work on the latest version, so it's a problem on your end.
