### ISSUE TITLE
Performancer 1.2.1 NodesCostraint + Finger FK Bones Bug

### ISSUE THREAD

**Issue by AsintotoX** [starstormhun/StarPlugins#29]
The previous issue has been solved, thank you! But sadly, when moving FK Bones that have been "tied" with NodesCostraint, for example to a folder, the FK "circle" doesn't change position until you click on the character.

To be more specific: I use an armature made up of multiple folders to have a more fluid animation. For example, the Hand FK Bone is the child of the "Hand | Anm" Folder, using NC. When I move the folder, all the FK circles remain in the same position, both the Hand and the fingers. The same happens when moving the FK Bones tied to another FK Bone, for example: Handholding, lol

This issue is only problematic to an handful of creators who make animation using a system of folders (AnnaAnon is the first one that comes to my mind, since they use an XYZ folder system), so it's not an high-priority bug.
But this plugin is quite helpful since I get 20 more fps while using it ahah

**Comment by AsintotoX** [comment]
On further inspection, when rotating a finger bone, the other bones of the finger don't move with it.

**Comment by starstormhun** [comment]
This issue only seems to exist when "Show All" is toggled on in the studio settings. In such cases the GuideObject optimisation seems to break down, so I'll disable it. In large scenes where the GuideObject optimisation has a tangible effect, I expect that option will be toggled the other way.

**Comment by starstormhun** [comment]
This issue is now fixed in v1.2.2, available on Discord or via compiling it yourself.
