### ISSUE TITLE
Enhancement - save expression data to scene

### ISSUE THREAD

**Issue by Tarried** [starstormhun/StarPlugins#5]
Could you modify the plugin to allow saving the expressions with the scene? The biggest drawback of using the original plugin was the expressions not saving, and we resorted to KKPE tricks.

If possible, please could you extend the ranges of the sliders?

**Comment by starstormhun** [comment]
Hey!
I have no current plans to further develop this plugin as I just needed it to work on males. I encourage you to fork the repo and try making the changes yourself, then you can submit a pull request.
